"""
Dara Studio Builder
Main source code storage

Contains generated file contents.
"""


CODES = {


"pubspec.yaml": """
name: dara_studio

description: Dara Studio code editor.

publish_to: none

version: 1.0.0


environment:

  sdk: ">=3.0.0 <4.0.0"


dependencies:

  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3

  file_picker: ^8.0.0


flutter:

  uses-material-design: true
""",



"README.md": """
# Dara Studio

A lightweight cross-platform code editor.

Generated by Dara Studio Builder.
""",



"lib/main.dart": """
import 'package:flutter/material.dart';

import 'core/app.dart';


void main() {

  runApp(
    const DaraStudioApp(),
  );

}
""",



"lib/core/config.dart": """
class AppConfig {

  static const String name =
      "Dara Studio";


  static const String version =
      "1.0.0";


  static const bool offlineFirst =
      true;

}
""",



"lib/core/constants.dart": """
import 'package:flutter/material.dart';


class AppConstants {


  static const Color background =
      Color(0xFF0D1117);


  static const Color panel =
      Color(0xFF161B22);


  static const double sidebarWidth =
      260;


}
""",



"lib/core/theme.dart": """
import 'package:flutter/material.dart';

import 'constants.dart';


class AppTheme {


  static ThemeData dark = ThemeData(

    brightness:
        Brightness.dark,


    scaffoldBackgroundColor:
        AppConstants.background,


  );


}
""",



"lib/core/state.dart": """
class AppState {


  String currentProject = "";


  String currentFile = "";


  bool terminalOpen = true;



}
""",



"lib/core/controller.dart": """
import 'state.dart';


class AppController {


  final AppState state =
      AppState();



  void openProject(String path){

    state.currentProject =
        path;

  }


}
""",



"lib/core/storage.dart": """
class StorageService {


  Future<void> save(
      String key,
      String value
  ) async {

  }



  Future<String?> read(
      String key
  ) async {

    return null;

  }


}
""",



"lib/core/services.dart": """
class ServiceContainer {


  final Map<Type, dynamic> services =
      {};


  void register<T>(T value){

    services[T] = value;

  }


}
"""

}